version: '3.8'

services:
  postgres:
    image: postgres:13.10
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - common_network
    restart: always

  backend:
    image: crocksgift/kittygram_backend:latest
    container_name: backend
    volumes:
      - media:/app/media
      - static:/app/collected_static
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - common_network
    restart: always

  frontend:
    image: crocksgift/kittygram_frontend:latest
    container_name: frontend
    volumes:
      - static:/app/build
    depends_on:
      - backend
    networks:
      - common_network
    restart: always

  gateway:
    image: crocksgift/kittygram_gateway:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    networks:
      - common_network
    restart: always

volumes:
  static:
  media:
  pg_data:

networks:
  common_network:
    driver: bridge

