name: CI/CD for Kittygram

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install flake8 pytest

    - name: Lint code
      run: flake8 .

    - name: Run tests
      run: pytest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/kittygram_backend ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/kittygram_backend

    - name: Deploy to server
      run: |
        ssh -i ${{ secrets.SSH_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF
          cd ~/ktgrm-test
          docker-compose pull
          docker-compose down
          docker-compose up -d EOF'
