name: Deploy Kittygram

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the Terraform action'
        required: true
        default: 'plan'
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        env:
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
          YC_TOKEN: ${{ secrets.YC_TOKEN }}
        run: terraform init
        working-directory: ./infra

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        env:
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
          YC_TOKEN: ${{ secrets.YC_TOKEN }}
        run: terraform plan -var="cloud_id=$YC_CLOUD_ID" -var="folder_id=$YC_FOLDER_ID" -var="token=$YC_TOKEN"
        working-directory: ./infra

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        env:
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
          YC_TOKEN: ${{ secrets.YC_TOKEN }}
        run: terraform apply -auto-approve -var="cloud_id=$YC_CLOUD_ID" -var="folder_id=$YC_FOLDER_ID" -var="token=$YC_TOKEN"
        working-directory: ./infra

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        env:
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
          YC_TOKEN: ${{ secrets.YC_TOKEN }}
        run: terraform destroy -auto-approve -var="cloud_id=$YC_CLOUD_ID" -var="folder_id=$YC_FOLDER_ID" -var="token=$YC_TOKEN"
        working-directory: ./infra
